# Generated by Django 4.1.7 on 2023-03-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('eggs', 'eggs'), ('g', 'grams'), ('Tbsp', 'tablespoon'), ('mL', 'milliliter')], max_length=4),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
